### ISSUE TITLE
NsfIntegrate30.grc is the same as NsfIntegrate60

### ISSUE THREAD

**Issue by zirdisyukur** [WVURAIL/gr-radio_astro#25]
Im not sure if its just the title and all the variables are changed appropriately but the ID and setup files for NsfIntegrate30.grc refer to NsfIntegrate60 and integrate60.not files.

I suspect why I can't run these files because it also looks for the Airspy when I am actually using RTL-SDR

**Comment by zirdisyukur** [comment]
And I managed to just change the device and bandwidth from 6M to 3M and the abs name to Integrate30 but I still run into issues with finding the Integrate30.not file (even though I can see it in the same directory as the python file)

"""IOError: [Errno 2] No such file or directory: 'Integrate30.not'"""

**Comment by glangsto** [comment]
Hello

Thanks for your email. 

I’m not sure what is causing this particular problem, but there is a work around.

If you are using the existing design, just change directories to “examples”,
then only run via python.

Ie run these commands:

cd ~/examples

python NsfIntegrate30.py

(or whatever design you are running).

You can create the designs in gnuradio-companion.  But if the
file is not found, just run the python file from the command line.

For some reason others are seeing the note (.not) file as missing.  I can not
reproduce this problem with my raspberry pi.   

Good Luck

Glen

**Comment by glangsto** [comment]
This issue has been fixed in the GNURadio 3.7.13 versions.   There are still problems with 3.8 and 3.9 GNURadio installation.  These are separate issues.
