### ISSUE TITLE
No makefile found

### ISSUE THREAD

**Issue by stroshynski** [WVURAIL/gr-radio_astro#26]
Hi! I am very new to radio astronomy and am trying to download this repo, but cannot get past the command `make`.  I receive the message:

make: *** No targets specified and no makefile found. Stop.

I downloaded Linux onto my Mac via VirtualBox, if that's any help. I have successfully made it through:

sudo apt-get install git

sudo apt-get install libyaml-dev

sudo apt-get install libssl-dev

sudo apt-get install python-dev

sudo apt-get install python-pip

sudo apt-get install python-apt

sudo pip install pyopengl pyopengl_accelerate

sudo apt-get install gnuradio gr-osmosdr

sudo apt-get install limesuite airspy

sudo apt-get install gqrx-sdr

git clone https://github.com/WVURAIL/gr-radio_astro.git

cd gr-radio_astro

mkdir build

cd build; cmake ..

What am I doing wrong and how do I fix it? Also, does this repo support the RTL-SDR Blog dongle? Thanks!

**Comment by glangsto** [comment]
Hi Sophia,

Glad to hear  you are learning about radio astronomy.

If you send us the error message, we might be better able to help.

So I guess you are using an RTL-SDR for input.   This can work,
but it does not work nearly as well as the other, wider bandwidth, SDRs.   
I like the Airspy-mini (6 MHZ) and others like the Airspy R2 (10 MHz).

Also gnu radio can directly be installed on a Mac, so VirtualBox step should work,
but is not necessary.

Attached is a test example I just ran a few minutes ago.

Best regards

Glen

**Comment by stroshynski** [comment]
Glen, 

I attached some screenshots. I hope they give you enough information.

Thanks,

Sophia
![image](https://user-images.githubusercontent.com/45516096/88187842-08a2a100-cc05-11ea-8685-ebf5c5925a4a.png)
![image](https://user-images.githubusercontent.com/45516096/88187851-0d675500-cc05-11ea-9837-bad6d2588d6f.png)
![image](https://user-images.githubusercontent.com/45516096/88187855-0fc9af00-cc05-11ea-8e92-3325d27868b6.png)

**Comment by glangsto** [comment]
Hello
Sorry it has taken so long to respond.   It appears you are trying to run within the GnurRadio 3.8 version.
Unfortunately this branch does not build in 3.8. yet.  On a Raspberry PI.  if you checkout the 

gr38_dev 

branch it is closer to working, but still under development.  The CMAKE step should work in this branch.

For more instructions  for building see https://github.com/WVURAIL/gr-radio_astro/wiki/Installing-gr-radio_astro
