### ISSUE TITLE
Test Errors with gr-radio_astro-gr38

### ISSUE THREAD

**Issue by zzsblac** [WVURAIL/gr-radio_astro#27]
I get test errors using OpenSuSE Leap 15.1 with gnuradio 3.8 maint. I've attached the LastTest.log.
[LastTest.log](https://github.com/WVURAIL/gr-radio_astro/files/5431389/LastTest.log)

**Comment by kbandura** [comment]
Try gr38 branch.  gr38_dev may or may not work at any given time.

**Comment by glangsto** [comment]
Hi Kevin and all,

I’ve only been updating gr38_dev.  

What is our strategy for transferring gr38_dev to gr38?

Most of gr38_dev seems to be working.

Thanks

Glen
