### ISSUE TITLE
gnuradio 3.8.2 not compatible

### ISSUE THREAD

**Issue by antoniopetre** [WVURAIL/gr-radio_astro#29]
Hello,
I tried to build the repo, but I obtained this error: 
``` Could not find a configuration file for package "Gnuradio" that is compatible with requested version "3.7.2".
  The following configuration files were considered but not accepted:
    /opt/local/share/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.2.0
```
What can I do in order to make it run? Also, is it compatible with MacOS?
Thank you!

**Comment by glangsto** [comment]
Hi Antonio Petre,

I’ve just checked that the WVURAIL code is compatible with Mac book Pro.

The good news is that WVURAIL is compatible with GNURadio 3.7.13.5,
as I just did the complete build process.

Ie:

mv gr-radio_astro gr-radio_astro-19Sep16
git clone http://github.com/WVURAIL/gr-radio_astro
cd gr-radio_astro
mkdir build
cd build
cmake ../
make 
sudo make install
cd ..
cd examples
ls
gnuradio-companion NsfIntegrate100.grc
history

This worked perfectly, although there were many warning messages.

The whole process took about 20 minutes.

Unfortunately, I’ve still not gotten the 3.8 (or 3.9) versions to build.

Best regards

Glen

PS We are just about to release a new, complete, Raspberry PI OS.   I’ll send
a link within the week.

**Comment by kbandura** [comment]
To run on GNURadio 3.8, instructions are here:  

https://github.com/WVURAIL/gr-radio_astro/wiki/Installing-gr-radio_astro#installing-gr-radio-astro-for-gnuradio-38

If using macports on a Mac to install gnuradio, then it should work there as well.

**Comment by glangsto** [comment]
Hi Kevin and all,

I’ve just been following, and updating the wiki entry given below.

I think I’ve gotten part of the c++ code to work in the 3.8 environment.
Ie python2 -> python3 and xml -> yml

One critical issue with the wiki was at the end, saying

develop code by checking out

gr38-dev

while actually this should have been

gr38_dev

Which I’ve just fixed on the wiki.   Could someone please confirm/check that
that is correct?

I’ve put back the test programs I wrote for my very first c++ modules to gnuradio

These are tested in /examples with

vectordemo.grc
and
vectordemo_c2.grc

which are the python only and c++ versions of the code.

Could someone pull the gr38_dev version and confirm these work for you too?

Thanks!

Glen

This much is working on a Raspberry Pi 4B with Ubuntu 20.10.
