### ISSUE TITLE
3 vector median

### ISSUE THREAD

**Issue by jpettingale** [WVURAIL/gr-radio_astro#30]
CMakeLists refers to vmedian2, but this is not included in the repository. Cmake fails on the missing file.

-- Configuring done
CMake Error at lib/CMakeLists.txt:42 (add_library):
  Cannot find source file:

    vmedian2_impl.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at lib/CMakeLists.txt:42 (add_library):
  No SOURCES given to target: gnuradio-radio_astro

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by glangsto** [comment]
Hello J. Pettingale,

Sorry about the “make" error.   FYI, I tried to create a
more efficient vector median code, (vmedian2).  Unfortunately
that did not work out.   I thought I removed vmedian2, but
unfortunately did not get everything.

I’ve fixed the code, pushed on one raspberry pi
and then pulled on another raspberry pi.

That build worked, so hopefully all is
good, after you do another “git pull”

I don’t recognize your email address.  Who are you and where
is your telescope?

Best regards

Glen Langston
Green Bank, WV
304-456-3032

**Comment by jpettingale** [comment]
Hi Glen, 

 

Thanks for fixing the repository, it works fine now.

 

I am a backyard astronomer and have built my own radio telescopes. Rather than write my own software, I am trying all the ready written software packages to see which works best with my setup, yours looks very useful! I am hoping to run everything from a Raspberry Pi and at the moment the software does not look as if it is too resource hungry. Some packages I have tried are just too much for a PI and need to be run from a fast computer or laptop. I am located in Scottsboro, Alabama.

 

Thank you for all the resources provided on the WVUrail website, they give me plenty to think about!

 

Kind regards

 

Jonathan Pettingale
