### ISSUE TITLE
note file path

### ISSUE THREAD

**Issue by raidfire99** [WVURAIL/gr-radio_astro#38]
I am having issues with the event write block, it can never find the .not file however I write the note file field, even with a blank field it bombs out looking for a file, from what I can see is it's always adding the prefix ./ to any path I configure.

Am I missing something in my setup for example a path in the conf file, everything else works fine, python paths look good, If i can find where the ./ is coming from I think it will be solved.

Issue is manifested in all detect examples and manually rewritten flows.

Ubuntu 18.04, gr3.7

**Comment by glangsto** [comment]
Hi raidfire99,
Sorry I missed your issue.   The notes files (.not) should all be in the directory you start the gnuradio design running in.
Some of the scripts for starting designs "cd" to the directory
gr-radio_astro/examples
or 
gr-radio_astro/examples/nsf
